image: docker:latest

services:
    - docker:dind

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u $HUB_USER -p $HUB_PASSWORD
    - apk --update add make

build:
    script:
        - make
