image: docker:latest

services:
  - docker:dind

build:
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker login -u ankitrgadiya -p $DOCKER_PASSWORD
        - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH/cgit:debian-apache .
        - docker tag $CI_REGISTRY/$CI_PROJECT_PATH/cgit:debian-apache ankitrgadiya/cgit:debian-apache
        - docker push $CI_REGISTRY/$CI_PROJECT_PATH/cgit:debian-apache
        - docker push ankitrgadiya/cgit:debian-apache

